import React, { useEffect, useState } from "react";
import SmartTaxiLogo from "../../components/ui/SmartTaxiLogo.jsx";
import legalDocuments from "../../legal/legal-content.json";

// Public, unauthenticated pages for the 5 lawyer-approved legal documents
// (smarttaxi.kz/legal, /legal/:id). Google Play's "App content" declaration
// and Apple's App Review both require a live, publicly reachable privacy
// policy URL — the in-app-only viewer in the mobile apps doesn't satisfy
// that, since reviewers and prospective users need to open it in a browser
// before installing anything. Content is generated by
// apps/web/scripts/extract-legal-content.mjs from the mobile app's
// legal_content.dart, which stays the single source of truth.
function docIdFromPath(path) {
  const match = path.match(/^\/legal\/([a-zA-Z]+)\/?$/);
  return match ? match[1] : null;
}

export default function LegalApp() {
  const [path, setPath] = useState(window.location.pathname);
  const activeId = docIdFromPath(path);
  const activeDoc = legalDocuments.find(doc => doc.id === activeId) || null;

  useEffect(() => {
    function handlePopState() {
      setPath(window.location.pathname);
      window.scrollTo(0, 0);
    }
    window.addEventListener("popstate", handlePopState);
    return () => window.removeEventListener("popstate", handlePopState);
  }, []);

  function navigate(nextPath) {
    window.history.pushState(null, "", nextPath);
    setPath(nextPath);
    window.scrollTo(0, 0);
  }

  return (
    <div className="legal-page">
      <header className="legal-header">
        <a
          href="/legal"
          className="legal-brand"
          onClick={event => {
            event.preventDefault();
            navigate("/legal");
          }}
        >
          <SmartTaxiLogo />
          <span>SmartTaxi</span>
        </a>
      </header>
      <main className="legal-main">
        {activeDoc ? <LegalDocumentView doc={activeDoc} onBack={() => navigate("/legal")} /> : <LegalHub onOpen={id => navigate(`/legal/${id}`)} />}
      </main>
      <footer className="legal-footer">
        <span>© {new Date().getFullYear()} SmartTaxi · smarttaxi.kz</span>
      </footer>
      <style>{legalStyles}</style>
    </div>
  );
}

function LegalHub({ onOpen }) {
  return (
    <>
      <h1>Юридические документы</h1>
      <p className="legal-lead">
        Документы, регулирующие использование мобильного приложения и веб-сайта SmartTaxi.
      </p>
      <div className="legal-doc-grid">
        {legalDocuments.map(doc => (
          <button
            type="button"
            key={doc.id}
            className="legal-doc-card"
            onClick={() => onOpen(doc.id)}
          >
            <strong>{doc.title}</strong>
            <span>{doc.lead.split("\n")[0]}</span>
          </button>
        ))}
      </div>
    </>
  );
}

function LegalDocumentView({ doc, onBack }) {
  return (
    <>
      <button type="button" className="legal-back" onClick={onBack}>
        ← Все документы
      </button>
      <h1>{doc.title}</h1>
      <p className="legal-lead" style={{ whiteSpace: "pre-line" }}>{doc.lead}</p>
      <div className="legal-sections">
        {doc.sections.map(section => (
          <section className="legal-section" key={section.title}>
            <h2>{section.title}</h2>
            <p style={{ whiteSpace: "pre-line" }}>{section.body}</p>
          </section>
        ))}
      </div>
    </>
  );
}

const legalStyles = `
.legal-page {
  min-height: 100svh;
  display: flex;
  flex-direction: column;
  background: #fffcf6;
  color: #241c0c;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
}
.legal-header {
  padding: 18px 24px;
  border-bottom: 1px solid rgba(120, 90, 20, .12);
}
.legal-brand {
  display: inline-flex;
  align-items: center;
  gap: 10px;
  text-decoration: none;
  color: #241c0c;
  font-weight: 900;
  font-size: 16px;
}
.legal-brand img { width: 30px; height: 30px; border-radius: 9px; }
.legal-main {
  flex: 1;
  width: 100%;
  max-width: 760px;
  margin: 0 auto;
  padding: 32px 20px 60px;
}
.legal-main h1 {
  font-size: 26px;
  font-weight: 950;
  margin: 0 0 8px;
}
.legal-lead {
  color: #7a6a45;
  font-size: 14px;
  line-height: 1.5;
  font-weight: 650;
  margin: 0 0 24px;
}
.legal-doc-grid {
  display: grid;
  gap: 12px;
}
.legal-doc-card {
  display: flex;
  flex-direction: column;
  gap: 4px;
  text-align: left;
  padding: 18px;
  background: #fff;
  border: 1px solid rgba(120, 90, 20, .14);
  border-radius: 20px;
  cursor: pointer;
  font: inherit;
  color: inherit;
}
.legal-doc-card strong { font-size: 15px; font-weight: 900; }
.legal-doc-card span { font-size: 12.5px; color: #7a6a45; font-weight: 650; }
.legal-back {
  border: none;
  background: none;
  color: #dfa21a;
  font-weight: 800;
  font-size: 13px;
  padding: 0;
  margin-bottom: 16px;
  cursor: pointer;
}
.legal-sections { display: grid; gap: 20px; }
.legal-section h2 {
  font-size: 14.5px;
  font-weight: 900;
  margin: 0 0 8px;
}
.legal-section p {
  font-size: 13.5px;
  line-height: 1.6;
  color: #3a2f18;
  margin: 0;
}
.legal-footer {
  padding: 20px;
  text-align: center;
  color: #a8996f;
  font-size: 12px;
}
`;
